image:
  file: .gitpod.Dockerfile

tasks:
  - name: slirp4netns
    command: |
      while ! test -f "/tmp/pid"; do
        sleep 0.1
      done
      sudo slirp4netns --configure --mtu=65520 --disable-host-loopback $(cat /tmp/pid) tap0
  - name: Tailscale
    command: |
      sudo unshare --user --map-root-user --net
      echo $$ > /tmp/pid
  - name: test
      while ! test -f "/tmp/pid"; do
        sleep 2
      done
      sudo nsenter -t $(cat /tmp/pid) -n tailscale --socket /tmp/tailscale.sock up
